### ISSUE TITLE
[MultiMC/PrismLauncher] [macOS] Release 1.0.0+: Failed to verify username!

### ISSUE THREAD

**Issue by ChampionCynthia** [MCPHackers/LaunchWrapper#7] opened 2024-01-01 13:25 UTC
Tested using Minecraft 1.1 on MultiMC 0.7.0 and PrismLauncher 8.0, macOS 10.14 Mojave.

Java:
```
$ java -version
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_392-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.392-b08, mixed mode)
```

## Problem
LaunchWrapper is run with:

```
--username <User> --session token:<ACCESS TOKEN>:<PROFILE ID> --gameDir /path/to/MultiMC/instances/1.1-1/.minecraft --assetsDir /path/to/MultiMC/instances/1.1-1/.minecraft/resources --resourcesProxyPort 11707 --skinProxy pre-1.8 --forceVsync
```

The game's log seems to confirm that both the username and the access token are forwarded to the game:

```
Setting user: <User>, token:<ACCESS TOKEN>:<PROFILE ID>
```

Yet, trying to connect to a Minecraft server with `online-mode=true` fails:

```
[INFO] Disconnecting <User> [/127.0.0.1:53603]: Failed to verify username!
```

The username is correct and skins work though.

I can connect just fine without LaunchWrapper (with and without the Betacraft proxies).

It should be noted that MultiMC doesn't replace existing libraries like LWJGL with MCPHackers's version.

## Cause
Using `tcpdump`, I determined that when run with LaunchWrapper, the client doesn't send anything to `session.minecraft.net`. The server actually accepts the connection but the client cannot verify itself and bails out.

**Without LaunchWrapper:**
```
# Client
127.0.0.1 > session.minecraft.net: HTTP: GET /game/joinserver.jsp?user=<User>&sessionId=<sessionId>&serverId=<serverId> HTTP/1.1
session.minecraft.net > 127.0.0.1: HTTP: HTTP/1.1 200 OK

# Server
127.0.0.1 > session.minecraft.net: HTTP: GET /game/checkserver.jsp?user=<User>&serverId=<serverId>
session.minecraft.net > 127.0.0.1: HTTP: HTTP/1.1 200 OK
```

**With LaunchWrapper:**
```
# Server only!
127.0.0.1 > session.minecraft.net: HTTP: GET /game/checkserver.jsp?user=<User>&serverId=<serverId>
session.minecraft.net > 127.0.0.1: HTTP: HTTP/1.1 200 OK
```

I know that the wrapper is programmed to properly make the query in [LegacyURLStreamHandler.java](https://github.com/MCPHackers/LaunchWrapper/blob/304d09d3b3622671f44260aa5354240f722c8a8c/src/main/java/org/mcphackers/launchwrapper/protocol/LegacyURLStreamHandler.java#L24C26-L24C26):

```java
if(path.equals("/game/joinserver.jsp"))
    return super.openConnection(new URL("http", "session.minecraft.net", path));
```

so I'm not sure as to where the bug lies.

**Comment by Lassebq** [comment] 2024-08-15 09:55
Duplicate of #5. However, it should be fixed now with latest commit. Please test

**Closed by Lassebq** 2024-08-15 09:55 UTC
